### ISSUE TITLE
Problem when running DVMpp code

### ISSUE THREAD

**Issue by Mipt179** [gdeskos/DVMpp#1]
Hello!
When i was trying to run DVM code with command "./DVM++ test.xml", i faced some problem with input file. 
Could anyone send me some sample input files and geometry files. Thank you very much.
![screenshot from 2018-03-23 13-18-36](https://user-images.githubusercontent.com/10219753/37824420-98af6f06-2e9d-11e8-87c7-dc01ce236515.png)

**Comment by gdeskos** [comment]
Hi,
You may use the two files I just uploaded as examples. Please notice that you will have to change the input and output directories in the xml file.
Cheers,
GD
